### ISSUE TITLE
failure to create wayland wl_display

### ISSUE THREAD

**Issue by tsteven4** [MirServer/graphics-core22#6]
When I launch a Qt6 based app using graphics-core22 I see
```
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
```
It seems like something like this is needed, perhaps in graphics/bin/graphics-core22-provider-wrapper:
https://github.com/snapcore/snapcraft/blob/77d3454d5a8e79cce8d543cd31cbf0a7b32b0e42/extensions/desktop/common/desktop-exports#L243-L268

If use "snap run --shell" to start, and paste that bit in before launching the app the message is gone.  I did notice that the link created is not deleted, so after that normal launching works.

**Comment by tsteven4** [comment]
My snap file is https://github.com/tsteven4/gpsbabel/blob/8533cc2a2f51d2f6255b6bfc3d4d8cd9d8cbd102/snap/snapcraft.yaml

**Comment by AlanGriffiths** [comment]
If you look at the examples provides as branches under https://github.com/MirServer/iot-example-graphical-snap/ you will see that the recommended approach is to use a `wayland-launch` wrapper that sets this up. (I know the examples are currently based on core20, but the approach remains the same with core22)
